[package]
name = "gapbuf"
version = "0.1.0"
authors = ["FrozenLib <frozenlib@users.noreply.github.com>"]
description = "Generic gap buffer."
homepage = "https://github.com/frozenlib/gapbuf-rs"
license = "MIT/Apache-2.0"
keywords = ["gap", "gapbuffer"]
categories = ["data-structures"]

[dependencies]

[dev-dependencies]
proptest = "0.8.6"