[package]
name = "gapbuf"
version = "0.1.1"
authors = ["FrozenLib"]
license = "MIT/Apache-2.0"
readme = "README.md"
repository = "https://github.com/frozenlib/gapbuf-rs"
documentation = "https://docs.frozenlib.net/gapbuf/gapbuf/"
keywords = ["gap", "gapbuffer"]
categories = ["data-structures"]
description = "Generic gap buffer."

[badges]
travis-ci = { repository = "frozenlib/gapbuf-rs" }

[dependencies]

[dev-dependencies]
proptest = "0.8.6"